def getDate() {
  Date date = new Date()
  return date.format('yyyyMMdd') as String
}

def genAemAwsStackBuilderConfigProfileName(architecture, configProfile) {
    config = configProfile.split('-')
    return config[0] + '-' + architecture + '-' + config[1] + '-' + config[2] + '-' + config[3] + '-' + config[4]
}

def date = getDate()
def fs_cp = genAemAwsStackBuilderConfigProfileName('full-set',"${params.AOC_CONFIG_PROFILE_STACK_BUILDER}")
def con_cp = genAemAwsStackBuilderConfigProfileName('consolidated',"${params.AOC_CONFIG_PROFILE_STACK_BUILDER}")

pipeline {
    agent {
        docker {
            image params.JENKINS_AGENT_DOCKER_IMAGE
            args params.JENKINS_AGENT_DOCKER_ARGS
        }
    }
    triggers {
        cron("H 13 * * 2,4")
    }
    environment {
        TMPDIR = "/tmp/shinesolutions/aem-opencloud-manager"
    }
    parameters {
        string(name: 'AOC_VERSION', defaultValue: 'internal-main', description: 'Version of aem-aws-stack-builder repo to archive')
        choice(name: 'AEM_VERSION', choices: ['65', '64'], description: 'AEM version to test')
        choice(name: 'OS_VERSION', choices: ['rhel7', 'amazon-linux2', 'rhel8'], description: 'OS version to test')
        choice(name: 'JDK_VERSION', choices: ['11', '8'], description: 'JDK version to test')
        booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', defaultValue: 'true', description: 'If activated SLACK notifications will be send out.')
        string(name: 'STACK_MANAGER_STACK_PREFIX', defaultValue: 'aoc-sm-sh3-' + date, description: 'Stack Manager Stack Prefix to create for the test.')
        string(name: 'STACK_PREFIX', defaultValue: 'aoc-sh3-' + date, description: 'AEM Stack Stack Prefix to create for the test.')
        string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', defaultValue: 'aws-rhel7-aem65-jdk11-sh', description: 'Name of the packer-aem configuration profile.')
        string(name: 'AOC_CONFIG_PROFILE_STACK_BUILDER', defaultValue: 'aem-rhel7-aem65-jdk11-sh', description: 'Name of the stack-builder configuration profile.')
        string(name: 'AOC_CONFIG_ARTIFACT_URL', defaultValue: 's3://aem-opencloud-manager/library/aws-rhel7-aem65-jdk11-sh3-internal-config-e2etest.tar.gz', description: 'URL to the AEM OpenCloud Configuration artifact.')
        string(name: 'AWS_LIBRARY_S3_BUCKET', defaultValue: 'aem-opencloud-manager', description: 'S3 bucket where the libraries are stored.')
        string(name: 'AWS_LIBRARY_S3_PATH', defaultValue: 'library', description: 'S3 path (of the specified S3 bucket) where the libraries are stored.')
        string(name: 'AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER', defaultValue: 'sandpit', description: 'Name of the AEM Stack Manager Messenger configuration profile.')
        string(name: 'AOC_CONFIG_PROFILE_AEM_TEST_SUITE', defaultValue: 'sandpit', description: 'Name of the AEM Test Suite configuration profile.')
        string(name: 'AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', defaultValue: 'aem-stack-manager-sandpit', description: 'Name of the AEM AWS Stack Builder configuration profile.')
        string(name: 'JENKINS_AGENT_DOCKER_IMAGE', defaultValue: 'shinesolutions/aem-platform-buildenv:latest', description: 'The name of Docker image to be used as Jenkins build pipeline agent.')
        string(name: 'JENKINS_AGENT_DOCKER_ARGS', defaultValue: "--user root -e AWS_DEFAULT_REGION=ap-southeast-2 -e https_proxy=http://forward-proxy.infracatalog.srv:3128/ -e http_proxy=http://forward-proxy.infracatalog.srv:3128/ -e no_proxy=localhost,127.0.0.1,169.254.169.254,169.254.0.0/16,elb.amazonaws.com,10.0.0.0/12,aemopencloud.cms,infracatalog.srv", description: 'The CLI args for Jenkins to use when running Docker CLI.')

    }

    stages {
        stage('Installation') {
            steps {
                build job: "aem-opencloud-${params.AOC_VERSION}/installation/aws/mirror-aem-opencloud-libraries",
                parameters: [
                  booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}")
                ]
                build job: "aem-opencloud-${params.AOC_VERSION}/installation/aws/mirror-stack-builder-libraries-${fs_cp}",
                parameters: [
                  booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}")
                ]
                build job: "aem-opencloud-${params.AOC_VERSION}/installation/aws/mirror-stack-builder-libraries-${con_cp}",
                parameters: [
                  booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}")
                ]
            }
        }
        stage('AMI Baking') {
            failFast true
            parallel {
            stage('Author') {
                steps {
                  retry(3) {
                    build job: "aem-opencloud-${params.AOC_VERSION}/machine-images/aws/${params.AOC_CONFIG_PROFILE_PACKER_AEM}/author",
                    parameters: [
                      booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                      string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', value: "${params.AOC_CONFIG_PROFILE_PACKER_AEM}"),
                    ]
                  }
                }
            }
            stage('Publish') {
                steps {
                  retry(3) {
                    build job: "aem-opencloud-${params.AOC_VERSION}/machine-images/aws/${params.AOC_CONFIG_PROFILE_PACKER_AEM}/publish",
                    parameters: [
                      booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                      string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', value: "${params.AOC_CONFIG_PROFILE_PACKER_AEM}"),
                    ]
                  }
                }
            }
            stage('Dispatcher') {
                steps {
                  retry(3) {
                    build job: "aem-opencloud-${params.AOC_VERSION}/machine-images/aws/${params.AOC_CONFIG_PROFILE_PACKER_AEM}/dispatcher",
                    parameters: [
                      booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                      string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', value: "${params.AOC_CONFIG_PROFILE_PACKER_AEM}"),
                    ]
                  }
                }
            }
            stage('Java') {
                steps {
                  retry(3) {
                    build job: "aem-opencloud-${params.AOC_VERSION}/machine-images/aws/${params.AOC_CONFIG_PROFILE_PACKER_AEM}/java",
                    parameters: [
                      booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                      string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', value: "${params.AOC_CONFIG_PROFILE_PACKER_AEM}"),
                    ]
                  }
                }
            }
            stage('Author-Publish-Dispatcher') {
                steps {
                  retry(3) {
                    build job: "aem-opencloud-${params.AOC_VERSION}/machine-images/aws/${params.AOC_CONFIG_PROFILE_PACKER_AEM}/author-publish-dispatcher",
                    parameters: [
                      booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                      string(name: 'AOC_CONFIG_PROFILE_PACKER_AEM', value: "${params.AOC_CONFIG_PROFILE_PACKER_AEM}"),
                    ]
                  }
                }
              }
            }
        }
        stage('Generate Configuration Package') {
            steps {
                script {
                   author_ami = sh (
                        script: "aws ec2 describe-images --filters \"Name=tag:Application Role,Values=author AMI\" \"Name=tag:OS Type,Values=${params.OS_VERSION}\" \"Name=tag:jdk_version,Values=${params.JDK_VERSION}\" \"Name=tag:Application Profile,Values=aem${params.AEM_VERSION}*\" --query \"sort_by(Images, &CreationDate)[-1].ImageId\" --output text",
                        returnStdout: true
                    ).trim()
                   publish_ami = sh (
                        script: "aws ec2 describe-images --filters \"Name=tag:Application Role,Values=publish AMI\" \"Name=tag:OS Type,Values=${params.OS_VERSION}\" \"Name=tag:jdk_version,Values=${params.JDK_VERSION}\" \"Name=tag:Application Profile,Values=aem${params.AEM_VERSION}*\" --query \"sort_by(Images, &CreationDate)[-1].ImageId\" --output text",
                        returnStdout: true
                    ).trim()
                   dispatcher_ami = sh (
                        script: "aws ec2 describe-images --filters \"Name=tag:Application Role,Values=dispatcher AMI\" \"Name=tag:OS Type,Values=${params.OS_VERSION}\" \"Name=tag:jdk_version,Values=${params.JDK_VERSION}\" \"Name=tag:Application Profile,Values=aem${params.AEM_VERSION}*\" --query \"sort_by(Images, &CreationDate)[-1].ImageId\" --output text",
                        returnStdout: true
                    ).trim()
                   java_ami = sh (
                        script: "aws ec2 describe-images --filters \"Name=tag:Application Role,Values=java AMI\" \"Name=tag:OS Type,Values=${params.OS_VERSION}\" \"Name=tag:jdk_version,Values=${params.JDK_VERSION}\" \"Name=tag:Application Profile,Values=aem${params.AEM_VERSION}*\" --query \"sort_by(Images, &CreationDate)[-1].ImageId\" --output text",
                        returnStdout: true
                    ).trim()
                   con_ami = sh (
                        script: "aws ec2 describe-images --filters \"Name=tag:Application Role,Values=author-publish-dispatcher AMI\" \"Name=tag:OS Type,Values=${params.OS_VERSION}\" \"Name=tag:jdk_version,Values=${params.JDK_VERSION}\" \"Name=tag:Application Profile,Values=aem${params.AEM_VERSION}*\" --query \"sort_by(Images, &CreationDate)[-1].ImageId\" --output text",
                        returnStdout: true
                    ).trim()
                    sh (
                      script: "echo -e \"---\\n#G enerated by AOC Test Pipeline\\n# AMI IDs for End2End Testing of AEM OpenCloud Manager\\nami_ids:\\n  author: ${author_ami}\\n  author_dispatcher: ${dispatcher_ami}\\n  author_publish_dispatcher: ${con_ami}\\n  chaos_monkey: ${java_ami}\\n  orchestrator: ${java_ami}\\n  publish: ${publish_ami}\\n  publish_dispatcher: ${dispatcher_ami}\" >> ZZZ_ami_ids.yaml"
                      )
                    sh (
                      script: "cp ZZZ_ami_ids.yaml ./aem-aws-stack-builder/${fs_cp}/ZZZ_ami_ids.yaml"
                      )
                    sh (
                      script: "cp ZZZ_ami_ids.yaml ./aem-aws-stack-builder/${con_cp}/ZZZ_ami_ids.yaml"
                      )
                    sh '''
                        tar \
                            --exclude='.git*' \
                            --exclude='.librarian*' \
                            --exclude='.tmp*' \
                            --exclude='.yamllint' \
                            --exclude='stage*' \
                            --exclude='.idea*' \
                            --exclude='.DS_Store*' \
                            --exclude='logs*' \
                            --exclude='*.retry' \
                            --exclude='*.iml' \
                            -cf aoc-config-e2etest.tar ./
                    '''
                    sh (
                            script: "gzip aoc-config-e2etest.tar"
                    )
                    sh (
                            script: "aws s3 cp aoc-config-e2etest.tar.gz ${params.AOC_CONFIG_ARTIFACT_URL}"
                    )
                }
            }
        }
        stage('FS Platform Testing') {
            parallel {
                stage('FS Platform') {
                    steps {
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${fs_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/full-set-platform",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-fs-platform" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-fs-platform"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${fs_cp}"),
                          string(name: 'DEPLOY_PACKAGE_ACTIVATE', value: "false"),
                          string(name: 'DEPLOY_PACKAGE_FORCE', value: "true"),
                          string(name: 'DEPLOY_PACKAGE_GROUP', value: "shinesolutions"),
                          string(name: 'DEPLOY_PACKAGE_NAME', value: "aem-helloworld-content"),
                          string(name: 'DEPLOY_PACKAGE_REPLICATE', value: "true"),
                          string(name: 'DEPLOY_PACKAGE_SOURCE', value: "https://repo.maven.apache.org/maven2/com/shinesolutions/aem-helloworld-content/0.0.2/aem-helloworld-content-0.0.2.zip"),
                          string(name: 'DEPLOY_PACKAGE_VERSION', value: "0.0.2"),
                          string(name: 'IMPORT_PACKAGE_GROUP', value: "shinesolutions"),
                          string(name: 'IMPORT_PACKAGE_NAME', value: "aem-helloworld")
                        ]
                    }
                }
                stage('Blue/Green') {
                    steps {
                        sleep 60
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${fs_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/full-set-blue-green",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX_BLUE', value: "${params.STACK_PREFIX}-blue-fs" ),
                          string(name: 'STACK_PREFIX_GREEN', value: "${params.STACK_PREFIX}-green-fs" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-fs-bg"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${fs_cp}")
                        ]
                    }
                }
                stage('Recovery') {
                    steps {
                        sleep 120
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${fs_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/full-set-recovery",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-fs-recovery" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-fs-recovery"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${fs_cp}")
                        ]
                    }
                }
                stage('Standby Promotion') {
                    steps {
                        sleep 180
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${fs_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/promote-author-standby-full-set",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-fs-promote" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-fs-promote"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${fs_cp}")
                        ]
                    }
                }
            }
        }
        stage('Consolidated Patform Testing') {
            steps {
                build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${con_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/consolidated-platform",
                parameters: [
                  booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                  string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-con-platform" ),
                  string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-con-platform"),
                  string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                  string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${con_cp}"),
                  string(name: 'DEPLOY_PACKAGE_ACTIVATE', value: "false"),
                  string(name: 'DEPLOY_PACKAGE_FORCE', value: "true"),
                  string(name: 'DEPLOY_PACKAGE_GROUP', value: "shinesolutions"),
                  string(name: 'DEPLOY_PACKAGE_NAME', value: "aem-helloworld-content"),
                  string(name: 'DEPLOY_PACKAGE_REPLICATE', value: "true"),
                  string(name: 'DEPLOY_PACKAGE_SOURCE', value: "https://repo.maven.apache.org/maven2/com/shinesolutions/aem-helloworld-content/0.0.2/aem-helloworld-content-0.0.2.zip"),
                  string(name: 'DEPLOY_PACKAGE_VERSION', value: "0.0.2"),
                  string(name: 'IMPORT_PACKAGE_GROUP', value: "shinesolutions"),
                  string(name: 'IMPORT_PACKAGE_NAME', value: "aem-helloworld")
                ]
            }
        }
        stage('Platform Security Testing') {
            parallel {
                stage('FS Security') {
                    steps {
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${fs_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/full-set-security",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-fs-sec" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-fs-sec"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${fs_cp}"),
                          string(name: 'PUBLISH_DISPATCHER_RECORD_SET', value: "aoc-fs-sh3-publish-dispatcher"),
                          string(name: 'AUTHOR_DISPATCHER_RECORD_SET', value: "aoc-fs-sh3-author-dispatcher"),
                          string(name: 'PUBLISH_DISPATCHER_HOSTED_ZONE', value: "shineworks.io"),
                          string(name: 'AUTHOR_DISPATCHER_HOSTED_ZONE', value: "aemopencloud.cms"),
                          string(name: 'AOC_CONFIG_PROFILE_AEM_TEST_SUITE', value: "full-set"),
                        ]
                    }
                }
                stage('Con Security') {
                    steps {
                        build job: "aem-opencloud-${params.AOC_VERSION}/testing/aws/${con_cp}-${params.AOC_CONFIG_PROFILE_AEM_STACK_MANAGER_MESSENGER}-${params.AOC_CONFIG_PROFILE_AEM_TEST_SUITE}-${params.AOC_STACK_MANAGER_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER}/consolidated-security",
                        parameters: [
                          booleanParam(name: 'ENABLE_SLACK_NOTIFICATIONS', value: "${params.ENABLE_SLACK_NOTIFICATIONS}"),
                          string(name: 'STACK_PREFIX', value: "${params.STACK_PREFIX}-con-sec" ),
                          string(name: 'STACK_MANAGER_STACK_PREFIX', value: "${params.STACK_MANAGER_STACK_PREFIX}-con-sec"),
                          string(name: 'AOC_CONFIG_ARTIFACT_URL', value: "${params.AOC_CONFIG_ARTIFACT_URL}"),
                          string(name: 'AOC_AEM_STACK_CONFIG_PROFILE_AEM_AWS_STACK_BUILDER', value: "${con_cp}"),
                          string(name: 'PUBLISH_DISPATCHER_RECORD_SET', value: "aoc-con-sh3-aem-consolidated"),
                          string(name: 'PUBLISH_DISPATCHER_HOSTED_ZONE', value: "aemopencloud.cms"),
                          string(name: 'AOC_CONFIG_PROFILE_AEM_TEST_SUITE', value: "consolidated"),
                        ]
                    }
                }
            }
        }
    }
    post {
        always {
          cleanWs()
        }
    }
}
